import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import test from "node:test";

// docs/COERCION-SCENARIOS.md is generated by scripts/coercion_scenarios.py.
// These tests need a Python 3.11+ interpreter; they skip cleanly if none is found.
const script = "scripts/coercion_scenarios.py";

function findPython() {
  for (const cmd of ["python", "py", "python3"]) {
    const r = spawnSync(cmd, ["-c", "import sys; print(sys.version_info >= (3, 11))"], { encoding: "utf8" });
    if (r.status === 0 && r.stdout.trim() === "True") return cmd;
  }
  return null;
}

const python = findPython();
const skip = python ? false : "no Python 3.11+ interpreter found (tried python, py, python3)";

function run(args) {
  return spawnSync(python, [script, ...args], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
}

test("docs/COERCION-SCENARIOS.md matches what the generator produces", { skip }, () => {
  const r = run(["--check"]);
  assert.equal(r.status, 0, `${r.stdout}${r.stderr}`);
});

test("the catalogue has at least 110 scenarios and meets every category minimum", { skip }, () => {
  const r = run(["--json"]);
  assert.equal(r.status, 0, r.stderr);
  const rows = JSON.parse(r.stdout);
  assert.ok(rows.length >= 110, `only ${rows.length} scenarios`);
  const minimum = { A: 12, B: 6, C: 10, D: 10, E: 10, F: 10, G: 10, H: 8, I: 8, J: 8, K: 12, L: 6, M: 4, N: 4, O: 4 };
  for (const [cat, min] of Object.entries(minimum)) {
    const n = rows.filter((row) => row.category === cat).length;
    assert.ok(n >= min, `category ${cat}: ${n} < ${min}`);
  }
});

test("no scenario reaches T3 (or T2) from detection alone; every T3 comes from H1 or H4", { skip }, () => {
  const rows = JSON.parse(run(["--json"]).stdout);
  for (const row of rows) {
    if (row.detection_only) assert.ok(row.peak <= 1, `${row.id} reached T${row.peak} from detection alone`);
    if (row.peak === 3) assert.match(row.rule, /^H[14]\b/, `${row.id}: T3 set by ${row.rule}`);
  }
});
